controller_list:
  - name: fake_left_arm_controller
    type: $(arg execution_type)
    joints:
      - torso_joint_b1
      - arm_left_joint_1_s
      - arm_left_joint_2_l
      - arm_left_joint_3_e
      - arm_left_joint_4_u
      - arm_left_joint_5_r
      - arm_left_joint_6_b
      - arm_left_joint_7_t
initial:  # Define initial robot poses.
#  - group: left_arm
#    pose: home

  []